version: "3"
services:
 reverseproxy:
   image: thanakijwanavit/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: thanakijwanavit/udagram-restapi-user:dev
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_DB: $POSTGRESS_DB 
   POSTGRESS_HOST: $POSTGRESS_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 backend-feed:
  image: thanakijwanavit/udagram-restapi-feed:dev
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_DB: $POSTGRESS_DB 
   POSTGRESS_HOST: $POSTGRESS_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 frontend:
  image: thanakijwanavit/udagram-frontend:dev
  ports:
   - "8100:80"
